
application: proyecto
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico


- url: /CSS
  static_dir: CSS

- url: /JS
  static_dir: JS

- url: /assets
  static_dir: assets

- url: /
  script: handlers.main.app

- url: /EncontrarHospitales
  script: handlers.encontrarHospitales.app

- url: /ListarRegistros
  script: handlers.Registros.registrosMedicos.app

- url: /ListarRegistros/AnhadirRegistro
  script: handlers.Registros.anhadirRegistro.app

- url: /ListarRegistros/BorrarRegistro
  script: handlers.Registros.borrarRegistro.app

- url: /ListarRegistros/EditarRegistro
  script: handlers.Registros.editarRegistro.app

- url: /ListarRegistros/BuscarRegistro
  script: handlers.Registros.buscarRegistro.app

- url: /ListarMedicamentos
  script: handlers.Medicamentos.gestionMedicamentos.app

- url: /ListarMedicamentos/AnhadirMedicamento
  script: handlers.Medicamentos.anhadirMedicamento.app

- url: /ListarMedicamentos/BorrarMedicamento
  script: handlers.Medicamentos.borrarMedicamento.app

- url: /ListarMedicamentos/EditarMedicamento
  script: handlers.Medicamentos.editarMedicamento.app

- url: /ListarMedicamentos/BuscarMedicamento
  script: handlers.Medicamentos.buscarMedicamento.app

- url: /ListarDiagnosticos
  script: handlers.Diagnosticos.gestionDiagnosticos.app

- url: /ListarDiagnosticos/AnhadirDiagnostico
  script: handlers.Diagnosticos.anhadirDiagnostico.app

- url: /ListarDiagnosticos/BorrarDiagnostico
  script: handlers.Diagnosticos.borrarDiagnostico.app

- url: /ListarDiagnosticos/EditarDiagnostico
  script: handlers.Diagnosticos.editarDiagnostico.app

- url: /ListarDiagnosticos/BuscarDiagnostico
  script: handlers.Diagnosticos.buscarDiagnostico.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"
